import 'dart:typed_data';

import 'package:photo_manager/photo_manager.dart';
import 'package:photo_manager_app/features/sync_session/domain/entities/sync_file.dart';
import 'package:photo_manager_app/features/sync_session/domain/services/media_thumbnail_source.dart';

/// Thumbnails of photos and videos generated by the system gallery (photo_manager).
class PhotoManagerThumbnailSource implements MediaThumbnailSource {
  const PhotoManagerThumbnailSource();

  @override
  Future<Uint8List?> thumbnail(SyncFile file) async {
    try {
      final asset = await AssetEntity.fromId(file.localId);
      if (asset == null) {
        return null;
      }
      final (width, height) = sizeFor(asset.width, asset.height);
      return await asset.thumbnailDataWithSize(
        ThumbnailSize(width, height),
        format: ThumbnailFormat.jpeg,
        quality: MediaThumbnailSource.jpegQuality,
      );
    } catch (_) {
      // Without a thumbnail the file is still uploaded; the gallery shows a placeholder
      return null;
    }
  }

  /// 512 px on the long side keeping the proportion, never bigger than the original.
  static (int, int) sizeFor(int width, int height) {
    const longSide = MediaThumbnailSource.longSide;
    if (width <= 0 || height <= 0) {
      return (longSide, longSide);
    }
    final longest = width > height ? width : height;
    if (longest <= longSide) {
      return (width, height);
    }
    final scale = longSide / longest;
    return ((width * scale).round().clamp(1, longSide), (height * scale).round().clamp(1, longSide));
  }
}
